# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# additional-spring-configuration-metadata.json

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:11802/test
    username: root
    password: root
    minimum-idle: 1
    maximum-pool-size: 5
    pool-name: SampleConnectionPool
    connectionTimeout: 10000
    validationTimeout: 5000
    idleTimeout: 600000
    minimumIdle: 3
    maximumPoolSize: 10
  flyway:
    enabled: false

logging:
  config: classpath:logback-local.xml