DROP TABLE article;

CREATE TABLE article
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    content    VARCHAR(255),
    title      VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO article (title, content) VALUES ('제목1', '내용1');
INSERT INTO article (title, content) VALUES ('제목2', '내용2');
INSERT INTO article (title, content) VALUES ('제목3', '내용3');

SELECT * FROM article;